name: paramtools-dev
channels:
  - conda-forge
dependencies:
  - "marshmallow>=3.0.0"
  - "numpy>=1.13"
  - "python-dateutil>=2.8.0"
  - pytest
  - fsspec
  - s3fs # required for tests but not most usage.
  - gcsfs # required for tests but not most usage.
  - pip:
      - pre-commit
      - black
      - flake8
