name: paramtools-dev
channels:
  - conda-forge
dependencies:
  - "marshmallow>=3.0.0"
  - "numpy>=1.13"
  - "python-dateutil>=2.8.0"
  - pytest
  - pip
  - pip:
    - pre-commit
    - black
    - flake8
