package:
  name: paramtools
  version: 0.0.0

requirements:
  build:
    - python
    - "marshmallow>=4.0.0"
    - "numpy>=1.13"
    - "python-dateutil>=2.8.0"

  run:
    - python
    - "marshmallow>=4.0.0"
    - "numpy>=1.13"
    - "python-dateutil>=2.8.0"

test:
  imports:
    - paramtools

about:
  home: https://github.com/PSLmodels/ParamTools
