name: Build and Deploy Jupyter Book
on:
  push:
    branches:
      - master
      - jupyter-docs
jobs:
  build-and-deploy:
    if: github.repository == 'PSLmodels/ParamTools'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: paramtools-dev
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false

      - name: Build # Build Jupyter Book
        run: |
          conda activate paramtools-dev
          jupyter-book build ./docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/_build/html # The folder the action should deploy.
